project:
  type: website

website:
  title: "Bayesian Learning Book"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notebooks.qmd
        text: Notebooks

format:
  html:
    theme:
      dark: superhero # litera, lumen, superhero, united
      light: lumen
    css: styles.css
    toc: true
    #monobackgroundcolor: #c3d0e6
callout-appearance: default


